---
- name: Detect OS and Generate Playbooks
  hosts: localhost
  gather_facts: true

  tasks:
      - name: Create new Playbook
        include_tasks: generate_playbook.yml
        vars:
        os_info: "{{ ansible_facts['ansible_kernel'] }}"
