# playbook to update pkg

- hosts: all
  tasks:
    - name: update package
      shell: sudo pkg update
      register: pkg_update
# print the output
    - name: print the output
      debug:
        msg: "{{ pkg_update.stdout }}"
# if msg contain "up to date" then print "pkg is up to date" else print "pkg is not up to date"
    - name: if fail
      debug:
        msg: "pkg is not up-to-date"
      when: pkg_update.stdout.find("up to date") == -1

    - name: print the output
      debug:
        msg: "pkg update fail"
      when: pkg_update.stdout.find("up to date") != 0

      ---
- name: Update FreeBSD packages
  hosts: your_freebsd_hosts
  become: yes
  ansible_become_method: sudo   # Puedes cambiar a "sudo" si prefieres usar sudo

  tasks:
    - name: Update package database
      pkgng:
        state: latest