# playbook to update pkg

- hosts: all
  tasks:
    - name: update package
      shell: sudo pkg update
      register: pkg_update
# print the output
    - name: print the output
      debug:
        msg: "{{ pkg_update.stdout }}"
# if msg contain "up to date" then print "pkg is up to date" else print "pkg is not up to date"
    - name: if fail
      debug:
        msg: "pkg is not up-to-date"
      when: pkg_update.stdout.find("up-to-date") == -1

    - name: print the output
      debug:
        msg: "pkg is up-to-date"
      when: pkg_update.stdout.find("up-to-date") != -1